using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace BardsCollegeExpansionAutoPatcher;

public static class Program
{
    private static readonly ModKey BceModKey = ModKey.FromNameAndExtension("kinggathcreations_bard.esm");
    private static readonly FormKey VanillaBardsCollegeCell = new(ModKey.FromNameAndExtension("Skyrim.esm"), 0x016A0C);
    private static readonly FormKey BceBardsCollegeCell = new(BceModKey, 0x01F0F8);

    private static Lazy<Settings> _settings = null!;

    public static async Task<int> Main(string[] args)
    {
        var pipeline = SynthesisPipeline.Instance;
        pipeline.SetAutogeneratedSettings<Settings>("Settings", "settings.json", out _settings);

        return await pipeline
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetTypicalOpen(GameRelease.SkyrimSE, "BardsCollegeExpansionPatch.esp")
            .Run(args);
    }

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var settings = _settings.Value;

        var bceModPresent = state.LoadOrder.ContainsKey(BceModKey);
        if (!bceModPresent)
        {
            Console.WriteLine($"[{nameof(BardsCollegeExpansionAutoPatcher)}] Required mod missing: {BceModKey.FileName}");
            return;
        }

        if (!state.PatchMod.ModHeader.MasterReferences.Any(master => master.Master == BceModKey))
        {
            state.PatchMod.ModHeader.MasterReferences.Add(new MasterReference { Master = BceModKey });
        }

        var csvPath = Path.Combine(AppContext.BaseDirectory, "BardsCollegeMatchingRefs.csv");
        if (!File.Exists(csvPath))
        {
            throw new FileNotFoundException($"Could not locate bundled CSV file at '{csvPath}'.", csvPath);
        }

        var refMapping = RefMapping.Load(csvPath);

        Console.WriteLine($"[{nameof(BardsCollegeExpansionAutoPatcher)}] BCE detected: {BceModKey.FileName}");
        Console.WriteLine($"[{nameof(BardsCollegeExpansionAutoPatcher)}] Loaded {refMapping.Cell1ToCell2.Count} reference mappings.");

        if (settings.Debug)
        {
            Console.WriteLine($"[{nameof(BardsCollegeExpansionAutoPatcher)}] Vanilla cell: {VanillaBardsCollegeCell}");
            Console.WriteLine($"[{nameof(BardsCollegeExpansionAutoPatcher)}] BCE cell: {BceBardsCollegeCell}");
            Console.WriteLine($"[{nameof(BardsCollegeExpansionAutoPatcher)}] Blacklist size: {settings.BlacklistedPlugins.Count}");
            Console.WriteLine($"[{nameof(BardsCollegeExpansionAutoPatcher)}] Cell1 CSV prefixes: {string.Join(", ", refMapping.Cell1LoadOrderPrefixes)}");
            Console.WriteLine($"[{nameof(BardsCollegeExpansionAutoPatcher)}] Cell2 CSV prefixes: {string.Join(", ", refMapping.Cell2LoadOrderPrefixes)}");
        }

        if (refMapping.Cell1LoadOrderPrefixes.Any(prefix => !string.Equals(prefix, "00", StringComparison.Ordinal)))
        {
            Console.WriteLine($"[{nameof(BardsCollegeExpansionAutoPatcher)}] Warning: Cell1 mapping contains non-00 load-order prefixes.");
        }
    }
}
